export const ADD_MARKER = 'ADD_MARKER';
export const REMOVE_MARKER = 'REMOVE_MARKER'
export const SET_MARKERS = 'SET_MARKERS';
export const SET_SUGGESTIONS = 'SET_SUGGESTIONS';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'
